[package]
authors = ["John Erickson <john.t.erickson@gmail.com"]
build = "build.rs"
name = "ghdl-rs"
version = "0.1.0"

[build-dependencies]
bindgen = "*"
execute = "*"

[dependencies]
dlopen = "0.1.8"