name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: check java version
      run: |
        java --version
        sudo update-alternatives --set java $(update-alternatives --list java | grep 17)
        java --version
    - name: Download Digital in a side-by-side directory
      run: |
        cd ..
        git clone https://github.com/johnterickson/Digital.git
        cd Digital
        mvn package -DskipTests
    - name: run build script
      run: ./build.sh
