name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: install deps
      run: |
        sudo apt update
        sudo apt install "ghdl*"
        ghdl --version
        ghdl-llvm --version
        sudo apt install libclang-dev
    - name: check versions
      run: |
        java --version
        sudo update-alternatives --set java $(update-alternatives --list java | grep 17)
        java --version
        mvn --version
    - name: run build script
      run: ./build.sh
