name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Digital in a side-by-side directory
      run: |
        cd ..
        wget https://github.com/hneemann/Digital/releases/download/v0.29/Digital.zip
        unzip Digital.zip
        cd Digital
        mkdir target
        cp Digital.jar target/
    - name: run build script
      run: ./build.sh
